apiVersion: v1
kind: Service
metadata:
  name: {{ include "relaymail-email-ses.fullname" . }}
  labels:
    {{- include "relaymail-email-ses.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "relaymail-email-ses.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
