apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: relaymail-email-ses
  namespace: relaymail
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: relaymail-email-ses
