image:
  repository: alikor/relaymail
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

serviceAccount:
  create: true
  name: relaymail-email-ses
  # Uncomment and set for IRSA on EKS:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/relaymail-irsa
  annotations: {}

env:
  RELAYMAIL_ENVIRONMENT: production
  RELAYMAIL_LOG_LEVEL: info
  RELAYMAIL_LOG_JSON: "true"
  RELAYMAIL_DRY_RUN: "false"
  RELAYMAIL_PRIMARY_PROVIDER: resend
  RELAYMAIL_FALLBACK_PROVIDERS: postmark,smtp2go
  RELAYMAIL_FALLBACK_ENABLED: "true"
  RELAYMAIL_AWS_SES_ENABLED: "false"
  RELAYMAIL_PROVIDER_TIMEOUT_SECONDS: "10"
  RELAYMAIL_GLOBAL_MAX_PER_MINUTE: "60"
  RELAYMAIL_STREAMS: transactional,marketing
  RELAYMAIL_STREAM_TRANSACTIONAL_ALLOWED_FROM_DOMAINS: mail.example.com
  RELAYMAIL_STREAM_TRANSACTIONAL_FROM_DEFAULT: "Example <no-reply@mail.example.com>"
  RELAYMAIL_STREAM_TRANSACTIONAL_REPLY_TO_DEFAULT: "Support <support@mail.example.com>"
  RELAYMAIL_STREAM_MARKETING_ALLOWED_FROM_DOMAINS: news.example.com
  RELAYMAIL_STREAM_MARKETING_FROM_DEFAULT: "Example <updates@news.example.com>"
  RELAYMAIL_STREAM_MARKETING_REPLY_TO_DEFAULT: "Marketing <reply@news.example.com>"
  RELAYMAIL_STREAM_MARKETING_REQUIRE_UNSUBSCRIBE: "true"
  RELAYMAIL_STREAM_MARKETING_REQUIRE_CONSENT_METADATA: "true"
  RELAYMAIL_RESEND_BASE_URL: https://api.resend.com
  RELAYMAIL_POSTMARK_BASE_URL: https://api.postmarkapp.com
  RELAYMAIL_POSTMARK_MESSAGE_STREAM: outbound
  RELAYMAIL_SMTP2GO_BASE_URL: https://api.smtp2go.com/v3
  RELAYMAIL_WEBHOOK_STORE_RAW_PAYLOADS: "false"
  RELAYMAIL_AWS_REGION: us-east-1
  RELAYMAIL_SQS_QUEUE_URL: ""
  RELAYMAIL_S3_BUCKET_ALLOWLIST: ""
  RELAYMAIL_IDEMPOTENCY_TABLE_NAME: ""
  RELAYMAIL_TRANSPORT_STATE_TABLE_NAME: ""
  RELAYMAIL_WORKER_CONCURRENCY: "4"
  RELAYMAIL_HTTP_BIND_ADDR: "0.0.0.0:8080"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8080

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

pdb:
  minAvailable: 1

podSecurityContext:
  runAsNonRoot: true

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
